services:
  - type: web
    name: conoce-tu-vehiculo-rd
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
    envVars:
      - key: VITE_API_BASE_URL
        value: https://conoce-tu-vehiculo-rd-api.onrender.com

  - type: web
    name: conoce-tu-vehiculo-rd-api
    runtime: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: BULL_BOARD_USER
        sync: false
      - key: BULL_BOARD_PASSWORD
        sync: false
      - key: REDIS_URL
        fromService:
          name: conoce-tu-vehiculo-rd-redis
          type: redis
          property: connectionString

  - type: worker
    name: conoce-tu-vehiculo-rd-email-worker
    runtime: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm run worker
    envVars:
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: REDIS_URL
        fromService:
          name: conoce-tu-vehiculo-rd-redis
          type: redis
          property: connectionString

  - type: redis
    name: conoce-tu-vehiculo-rd-redis
    plan: free
    ipAllowList: []
